### ISSUE TITLE
contracts: fresh build fails — rust-toolchain pinned below edition2024, plus 3 type errors on 1.88

### ISSUE THREAD

**Issue by Emeka-12** [Agropush/AgroPush#1]
## Summary

`cargo build` in `contracts/amana_escrow/` fails on a completely fresh checkout, in two stages. This blocks anyone trying to build/test/deploy the contract for the first time.

## Reproduction

```bash
cd contracts/amana_escrow
cargo build
```

**Stage 1 — toolchain too old for the pinned edition:**

```
error: failed to parse manifest at `.../contracts/amana_escrow/Cargo.toml`
Caused by:
  feature `edition2024` is required
  The package requires the Cargo feature called `edition2024`, but that feature is not
  stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
```

`rust-toolchain.toml` pins `channel = "1.81.0"`, but `Cargo.toml` sets `edition = "2024"`, which requires Cargo 1.85+.

**Stage 2 — after bumping the toolchain to 1.88 (`rustup toolchain install 1.88.0` + `rust-toolchain.toml` → `1.88.0`), 3 real type errors surface:**

```
error[E0283]: type annotations needed
   --> amana_escrow/src/lib.rs:744:61
    |
744 |             .set(&DataKey::ProposalApprovals(proposal_id), &Vec::new(&env));
    |                                                             ^^^^^^^^ cannot infer type of the type parameter `T`

error[E0283]: type annotations needed
   --> amana_escrow/src/lib.rs:795:61
    |
795 |             .set(&DataKey::ProposalApprovals(proposal_id), &Vec::new(&env));
    |                                                             ^^^^^^^^ cannot infer type of the type parameter `T`

error[E0308]: mismatched types
   --> amana_escrow/src/lib.rs:845:31
    |
845 |         if approvals.len() >= config.threshold as usize {
    |            ---------------    ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `usize`
```

## Root cause & exact fix

Elsewhere in the same file (line 825), `ProposalApprovals` is read back as `Vec<Address>` — so lines 744 and 795 just need the same type annotation Rust can no longer infer on its own:

```diff
- .set(&DataKey::ProposalApprovals(proposal_id), &Vec::new(&env));
+ .set(&DataKey::ProposalApprovals(proposal_id), &Vec::<Address>::new(&env));
```
(both occurrences, lines 744 and 795)

Line 845: `approvals.len()` already returns `u32`, and `config.threshold` is `u32` — the `as usize` cast is unnecessary and wrong:

```diff
- if approvals.len() >= config.threshold as usize {
+ if approvals.len() >= config.threshold {
```

## Acceptance criteria

- [ ] `rust-toolchain.toml`'s pinned channel supports `edition = "2024"` (1.88.0 confirmed working, or newer — note some newer toolchains hit unrelated dependency-compatibility errors in `ethnum`/`rand_core`, so verify `cargo build` actually succeeds before picking a version)
- [ ] The 3 type errors above are fixed as described
- [ ] `cargo build` and `cargo test` succeed on a completely fresh clone with no other changes

## Notes

This likely isn't caught by CI because the required CI gate's toolchain setup (`.github/workflows/ci.yml`) may pin a different/compatible version than what's in `rust-toolchain.toml` — worth double-checking those stay in sync as part of this fix.
